apiVersion: v1
kind: Pod
metadata:
  name: gossip-backend
  labels:
    app: backend
spec:
  containers:
  - name: gossip-server
    image: jeasterman/gossip_main
    ports:
    - containerPort: 33957