apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: ramsey-network
  namespace: default
spec:
  podSelector:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: ramsey-backend
    ports:
    - protocol: TCP
      port: 57339
    - protocol: TCP 
      port: 33957
