kind: Service
apiVersion: v1
metadata:
  name: ramsey-service
spec:
  type: NodePort
  selector:
    app: ramsey
  ports:
    - protocol: TCP
      port: 57339
      nodePort: 30080
  externalIPs: 
    - 169.231.235.174
